/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IPrimitiveLiquidityCallback } from "../IPrimitiveLiquidityCallback";

export class IPrimitiveLiquidityCallback__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPrimitiveLiquidityCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPrimitiveLiquidityCallback;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "delRisky",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "delStable",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "allocateCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "delRisky",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "delStable",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "removeCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
