/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IPrimitiveLendingCallback } from "../IPrimitiveLendingCallback";

export class IPrimitiveLendingCallback__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPrimitiveLendingCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPrimitiveLendingCallback;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "delLiquidity",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "delRisky",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "delStable",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "borrowCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "delStable",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "repayFromExternalCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
