/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IPrimitiveEngineActionsInterface extends ethers.utils.Interface {
  functions: {
    "allocate(bytes32,address,uint256,bool,bytes)": FunctionFragment;
    "borrow(bytes32,uint256,uint256,bytes)": FunctionFragment;
    "claim(bytes32,uint256)": FunctionFragment;
    "create(uint256,uint64,uint32,uint256,uint256,bytes)": FunctionFragment;
    "deposit(address,uint256,uint256,bytes)": FunctionFragment;
    "lend(bytes32,uint256)": FunctionFragment;
    "remove(bytes32,uint256,bool,bytes)": FunctionFragment;
    "repay(bytes32,address,uint256,bool,bytes)": FunctionFragment;
    "swap(bytes32,bool,uint256,uint256,bool,bytes)": FunctionFragment;
    "withdraw(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "allocate",
    values: [BytesLike, string, BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "borrow",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "create",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lend",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "remove",
    values: [BytesLike, BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "repay",
    values: [BytesLike, string, BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [BytesLike, boolean, BigNumberish, BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "allocate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "borrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lend", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "remove", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {};
}

export class IPrimitiveEngineActions extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IPrimitiveEngineActionsInterface;

  functions: {
    allocate(
      poolId: BytesLike,
      owner: string,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "allocate(bytes32,address,uint256,bool,bytes)"(
      poolId: BytesLike,
      owner: string,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    borrow(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      maxPremium: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "borrow(bytes32,uint256,uint256,bytes)"(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      maxPremium: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claim(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "claim(bytes32,uint256)"(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    create(
      strike: BigNumberish,
      sigma: BigNumberish,
      time: BigNumberish,
      riskyPrice: BigNumberish,
      delLiquidity: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "create(uint256,uint64,uint32,uint256,uint256,bytes)"(
      strike: BigNumberish,
      sigma: BigNumberish,
      time: BigNumberish,
      riskyPrice: BigNumberish,
      delLiquidity: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deposit(
      owner: string,
      delRisky: BigNumberish,
      delStable: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "deposit(address,uint256,uint256,bytes)"(
      owner: string,
      delRisky: BigNumberish,
      delStable: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lend(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "lend(bytes32,uint256)"(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    remove(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "remove(bytes32,uint256,bool,bytes)"(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    repay(
      poolId: BytesLike,
      owner: string,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "repay(bytes32,address,uint256,bool,bytes)"(
      poolId: BytesLike,
      owner: string,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swap(
      poolId: BytesLike,
      addXRemoveY: boolean,
      deltaOut: BigNumberish,
      deltaInMax: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "swap(bytes32,bool,uint256,uint256,bool,bytes)"(
      poolId: BytesLike,
      addXRemoveY: boolean,
      deltaOut: BigNumberish,
      deltaInMax: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      delRisky: BigNumberish,
      delStable: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "withdraw(uint256,uint256)"(
      delRisky: BigNumberish,
      delStable: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  allocate(
    poolId: BytesLike,
    owner: string,
    delLiquidity: BigNumberish,
    fromMargin: boolean,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "allocate(bytes32,address,uint256,bool,bytes)"(
    poolId: BytesLike,
    owner: string,
    delLiquidity: BigNumberish,
    fromMargin: boolean,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  borrow(
    poolId: BytesLike,
    delLiquidity: BigNumberish,
    maxPremium: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "borrow(bytes32,uint256,uint256,bytes)"(
    poolId: BytesLike,
    delLiquidity: BigNumberish,
    maxPremium: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claim(
    poolId: BytesLike,
    delLiquidity: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "claim(bytes32,uint256)"(
    poolId: BytesLike,
    delLiquidity: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  create(
    strike: BigNumberish,
    sigma: BigNumberish,
    time: BigNumberish,
    riskyPrice: BigNumberish,
    delLiquidity: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "create(uint256,uint64,uint32,uint256,uint256,bytes)"(
    strike: BigNumberish,
    sigma: BigNumberish,
    time: BigNumberish,
    riskyPrice: BigNumberish,
    delLiquidity: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deposit(
    owner: string,
    delRisky: BigNumberish,
    delStable: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "deposit(address,uint256,uint256,bytes)"(
    owner: string,
    delRisky: BigNumberish,
    delStable: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lend(
    poolId: BytesLike,
    delLiquidity: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "lend(bytes32,uint256)"(
    poolId: BytesLike,
    delLiquidity: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  remove(
    poolId: BytesLike,
    delLiquidity: BigNumberish,
    fromMargin: boolean,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "remove(bytes32,uint256,bool,bytes)"(
    poolId: BytesLike,
    delLiquidity: BigNumberish,
    fromMargin: boolean,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  repay(
    poolId: BytesLike,
    owner: string,
    delLiquidity: BigNumberish,
    fromMargin: boolean,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "repay(bytes32,address,uint256,bool,bytes)"(
    poolId: BytesLike,
    owner: string,
    delLiquidity: BigNumberish,
    fromMargin: boolean,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swap(
    poolId: BytesLike,
    addXRemoveY: boolean,
    deltaOut: BigNumberish,
    deltaInMax: BigNumberish,
    fromMargin: boolean,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "swap(bytes32,bool,uint256,uint256,bool,bytes)"(
    poolId: BytesLike,
    addXRemoveY: boolean,
    deltaOut: BigNumberish,
    deltaInMax: BigNumberish,
    fromMargin: boolean,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    delRisky: BigNumberish,
    delStable: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "withdraw(uint256,uint256)"(
    delRisky: BigNumberish,
    delStable: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    allocate(
      poolId: BytesLike,
      owner: string,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    "allocate(bytes32,address,uint256,bool,bytes)"(
      poolId: BytesLike,
      owner: string,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    borrow(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      maxPremium: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "borrow(bytes32,uint256,uint256,bytes)"(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      maxPremium: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claim(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "claim(bytes32,uint256)"(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    create(
      strike: BigNumberish,
      sigma: BigNumberish,
      time: BigNumberish,
      riskyPrice: BigNumberish,
      delLiquidity: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        poolId: string;
        delRisky: BigNumber;
        delStable: BigNumber;
      }
    >;

    "create(uint256,uint64,uint32,uint256,uint256,bytes)"(
      strike: BigNumberish,
      sigma: BigNumberish,
      time: BigNumberish,
      riskyPrice: BigNumberish,
      delLiquidity: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        poolId: string;
        delRisky: BigNumber;
        delStable: BigNumber;
      }
    >;

    deposit(
      owner: string,
      delRisky: BigNumberish,
      delStable: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "deposit(address,uint256,uint256,bytes)"(
      owner: string,
      delRisky: BigNumberish,
      delStable: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    lend(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "lend(bytes32,uint256)"(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    remove(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { delRisky: BigNumber; delStable: BigNumber }
    >;

    "remove(bytes32,uint256,bool,bytes)"(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { delRisky: BigNumber; delStable: BigNumber }
    >;

    repay(
      poolId: BytesLike,
      owner: string,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        delRisky: BigNumber;
        delStable: BigNumber;
        premium: BigNumber;
      }
    >;

    "repay(bytes32,address,uint256,bool,bytes)"(
      poolId: BytesLike,
      owner: string,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        delRisky: BigNumber;
        delStable: BigNumber;
        premium: BigNumber;
      }
    >;

    swap(
      poolId: BytesLike,
      addXRemoveY: boolean,
      deltaOut: BigNumberish,
      deltaInMax: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "swap(bytes32,bool,uint256,uint256,bool,bytes)"(
      poolId: BytesLike,
      addXRemoveY: boolean,
      deltaOut: BigNumberish,
      deltaInMax: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      delRisky: BigNumberish,
      delStable: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdraw(uint256,uint256)"(
      delRisky: BigNumberish,
      delStable: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    allocate(
      poolId: BytesLike,
      owner: string,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "allocate(bytes32,address,uint256,bool,bytes)"(
      poolId: BytesLike,
      owner: string,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    borrow(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      maxPremium: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "borrow(bytes32,uint256,uint256,bytes)"(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      maxPremium: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claim(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "claim(bytes32,uint256)"(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    create(
      strike: BigNumberish,
      sigma: BigNumberish,
      time: BigNumberish,
      riskyPrice: BigNumberish,
      delLiquidity: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "create(uint256,uint64,uint32,uint256,uint256,bytes)"(
      strike: BigNumberish,
      sigma: BigNumberish,
      time: BigNumberish,
      riskyPrice: BigNumberish,
      delLiquidity: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deposit(
      owner: string,
      delRisky: BigNumberish,
      delStable: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "deposit(address,uint256,uint256,bytes)"(
      owner: string,
      delRisky: BigNumberish,
      delStable: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lend(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "lend(bytes32,uint256)"(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    remove(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "remove(bytes32,uint256,bool,bytes)"(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    repay(
      poolId: BytesLike,
      owner: string,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "repay(bytes32,address,uint256,bool,bytes)"(
      poolId: BytesLike,
      owner: string,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swap(
      poolId: BytesLike,
      addXRemoveY: boolean,
      deltaOut: BigNumberish,
      deltaInMax: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "swap(bytes32,bool,uint256,uint256,bool,bytes)"(
      poolId: BytesLike,
      addXRemoveY: boolean,
      deltaOut: BigNumberish,
      deltaInMax: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      delRisky: BigNumberish,
      delStable: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "withdraw(uint256,uint256)"(
      delRisky: BigNumberish,
      delStable: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allocate(
      poolId: BytesLike,
      owner: string,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "allocate(bytes32,address,uint256,bool,bytes)"(
      poolId: BytesLike,
      owner: string,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    borrow(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      maxPremium: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "borrow(bytes32,uint256,uint256,bytes)"(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      maxPremium: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claim(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "claim(bytes32,uint256)"(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    create(
      strike: BigNumberish,
      sigma: BigNumberish,
      time: BigNumberish,
      riskyPrice: BigNumberish,
      delLiquidity: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "create(uint256,uint64,uint32,uint256,uint256,bytes)"(
      strike: BigNumberish,
      sigma: BigNumberish,
      time: BigNumberish,
      riskyPrice: BigNumberish,
      delLiquidity: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deposit(
      owner: string,
      delRisky: BigNumberish,
      delStable: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "deposit(address,uint256,uint256,bytes)"(
      owner: string,
      delRisky: BigNumberish,
      delStable: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lend(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "lend(bytes32,uint256)"(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    remove(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "remove(bytes32,uint256,bool,bytes)"(
      poolId: BytesLike,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    repay(
      poolId: BytesLike,
      owner: string,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "repay(bytes32,address,uint256,bool,bytes)"(
      poolId: BytesLike,
      owner: string,
      delLiquidity: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swap(
      poolId: BytesLike,
      addXRemoveY: boolean,
      deltaOut: BigNumberish,
      deltaInMax: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "swap(bytes32,bool,uint256,uint256,bool,bytes)"(
      poolId: BytesLike,
      addXRemoveY: boolean,
      deltaOut: BigNumberish,
      deltaInMax: BigNumberish,
      fromMargin: boolean,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      delRisky: BigNumberish,
      delStable: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "withdraw(uint256,uint256)"(
      delRisky: BigNumberish,
      delStable: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
